### PR TITLE
Integrate components to landing page

### LINKED ISSUE #46: Integrate Landing Page
All landing core components are done, lay them out on the landing page

### PR DESCRIPTION
**Pull request by xTh3Unkn0wnx**
IPhone 14 Pro Display:
Screenshot 2024-07-24 132357

Google Chrome IPad Pro resolution
Screenshot 2024-07-24 121909
Normal Laptop Resolution (14 inch QHD Display):
Screenshot 2024-07-24 121950
Screenshot 2024-07-24 122006

- Added all the components related to landing page in components/landing folder
- Closes #46

### CODE REVIEW

**Comment by xTh3Unkn0wnx** [comment]
I did notice some conflicts with the style when its down to a mobile phone when I used the IPhone 14 screen to see how it looks, didn't change the styling since I think its not covered under this issue, but if you want me to try update the styling I can try

**Comment by khandrew1** [comment]
can you attach the iphone screenshot the pr as well?

**Comment by xTh3Unkn0wnx** [comment]
@khandrew1 Ok just update the PR by adding the photos above the IPad display images samples 

The issue I notice is that the header is wide that it makes it scrollable horizontally on IPhone/Mobile display

**Comment by khandrew1** [comment]
oh yeah, def looks like a navbar issue as responsiveness on that seems to be taking a while (its a tough issue). also if ur on a laptop make sure you arent zoomed in with the trackpad, pinch out as much as you can; either way you shouldnt have to worry about it

will take a closer look with a formal review soon

**Review by khandrew1 — APPROVED** [review]

**Pull request merged**
