### PR TITLE
Create Custom Toolbar for Calendar 

### LINKED ISSUE #81: Custom Toolbar
- Create a custom toolbar for the Calendar, the skeleton is already there

- 
image

### PR DESCRIPTION
**Pull request by xTh3Unkn0wnx**
IPhone Display:
Screenshot 2024-08-16 203403

IPad Pro Display:
Screenshot 2024-08-16 203430

Laptop (QHD) Display:
Screenshot 2024-08-16 203459

- Made changes to the toolbar component for the calendar
- Imported two logos from react icons for both buttons
- Closes #81

### CODE REVIEW

**Comment by khandrew1** [comment]
Why is the text black? This issue also meant to change the toolbar to look exactly like the design, this calendar is a starter that you are definitely allowed to modify.

image

You need this change too and make sure its laid out like the design with them spread to each edge

**Comment by xTh3Unkn0wnx** [comment]
Ok will make the changes soon, also for the mobile and iPad view, is it ok for the buttons be below the data and arrows buttons or you want them to be on the same line regardless of view width?

**Comment by xTh3Unkn0wnx** [comment]
IPhone Pro 14 Display:
Screenshot 2024-08-17 213748

IPad Air Display:
Screenshot 2024-08-17 213737

Laptop display HD:
Screenshot 2024-08-17 213620

- Changes styles to better suit each display sizes
- Added the text-ai-black to texts for arrows and date
-  Used text-white for the text color for buttons, 
-  Made the buttons more rounded
-  Closes #81

**Comment by xTh3Unkn0wnx** [comment]
Ok I am pretty sure I resolved the back color text issue but not too sure for the text-color for the buttons since it a blue button with white text based on the screenshot in the issues. I used text-white since we seem to have no color for white. If you wanted me to use the ai-gray or ai-black I will change the colors immediately

**Comment by khandrew1** [comment]
Yeah, using white just cause there's no specific white color, I want the buttons changed though, I want it to look like the design with just arrows and none of the circles

**Comment by xTh3Unkn0wnx** [comment]
IPhone 14 Pro Display:
Screenshot 2024-08-18 131623

IPad Air Display:
Screenshot 2024-08-18 131640

HD Laptop Display:
Screenshot 2024-08-18 131701

- Got rid of some of the styling that makes the circle visible. The circle is technically there but is not visible to the user
-  Got rid of some styling from the template that I saw no longer fit the new look or got in the way of the envisioned look
-  Closes #81

**Comment by xTh3Unkn0wnx** [comment]
Also not sure if the date and arrows are too big for the mobile view but I will let you decide on that, should be an easy fix anyway.

**Review by khandrew1 — DISMISSED** [review]

**Comment by khandrew1** [comment]
Actually can we see how it would look like if the buttons were next to each other on mobile?

**Comment by xTh3Unkn0wnx** [comment]
IPhone 14 Pro Display:
Screenshot 2024-08-18 161648

IPad Air Display:
Screenshot 2024-08-18 161657

HD Laptop Display:
Screenshot 2024-08-18 161710

- Edit styles so that the buttons can be side by side in mobile view
-  Made the text and button smaller to help fit in the space in mobile view
-  Used truncate to make texts/contents in the button shrink down
-  Added more styles to help counteract some of the changes made for the mobile view
-  Closes #81

**Comment by khandrew1** [comment]
looking great, would be greater if you could make text smaller and icons bigger on mobile somehow

**Comment by xTh3Unkn0wnx** [comment]
Ok while testing with and without truncate it make the icons smaller than what they are supposed to be. The mobile view you see above is the one with truncate class and this is on one without it. Also I used the smallest class available for text text-xs
Screenshot 2024-08-18 165744

**Comment by xTh3Unkn0wnx** [comment]
IPhone 14 Pro Display:
Screenshot 2024-08-18 172021

IPad Air Display:
Screenshot 2024-08-18 172031

HD Laptop Display:
Screenshot 2024-08-18 172043


- Used custom tailwind text-[9px] to achieve small text smaller than the available text-xs class
- Made icons a bit bigger for all views
- Closes #81

**Comment by khandrew1** [comment]
Looks great!

**Review by khandrew1 — APPROVED** [review]

**Pull request merged**
